
// This file was auto-generated by ML.NET Model Builder. 

using Disco_Recommendations_FollowerModel;

// Create single instance of sample data from first line of dataset for model input
FollowingModel.ModelInput sampleData = new FollowingModel.ModelInput()
{
    _1_2 = 3F,
    _1_4 = 1F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual _1 with predicted _1 from sample data...\n\n");


Console.WriteLine($"_1: {3F}");
Console.WriteLine($"_1_2: {3F}");
Console.WriteLine($"_1_4: {1F}");


var predictionResult = FollowingModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted _1: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

